"""index in id_api

Revision ID: 3fed3f10a974
Revises: 0a2f401c4725
Create Date: 2025-11-03 12:34:40.140165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fed3f10a974'
down_revision: Union[str, Sequence[str], None] = '0a2f401c4725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_id_api'), 'product', ['id_api'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id_api'), table_name='product')
    # ### end Alembic commands ###
